# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile

before_install:
- gem update cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail
- xcodebuild -workspace Example/DisPlayers-Audio-Visualizers.xcworkspace -scheme DisPlayers-Audio-Visualizers-Example -sdk iphonesimulator10.0 -destination "OS=10.0,name=iPhone 7 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
- pod lib lint --allow-warnings
